name: yt_workspace

environment:
  sdk: ^3.10.3

dev_dependencies:
  melos: ^7.4.0
  publish_tools: ^1.0.0+11

workspace:
  - packages/yt
  - packages/yt_cli

melos:
  packages:
  - packages/**

  command:
    version:
      branch: main
      message: "chore(release): publish %s"

  bootstrap:
    runPubGetInParallel: false
    usePubspecOverrides: true

  scripts:
    lint:all:
      run: melos run analyze && melos run format
      description: Run all static analysis checks.

    # publish:all:
    #   run: melos run publish:dart && melos run publish:flutter
    #   description: Run publish for all packages.

    dep:
      exec: dart pub get

    build:
      exec: dart run build_runner build

    build:delete:
      run: false
      steps:
        - melos exec --scope="activation_config" -- "dart run build_runner build --delete-conflicting-outputs"
        - melos exec --ignore="activation_config" -- "dart run build_runner build --delete-conflicting-outputs"

    prep:lib:
      # run: melos run build && melos run meta && melos run markdown && melos run format && melos run analyze
      run: melos run meta && melos run markdown && melos run format && melos run analyze
      description: Run prep steps for lib and cli.

    # prep:flutter:
    #   run: melos run build && melos run meta && melos run markdown && melos run analyze && melos run format
    #   description: Run prep steps Flutter.

    ## TODO: Add commit steps for Dart and Flutter packages.

    commit:lib:
      run: melos exec --ignore="yt_cli" git add .; git commit -m "$(cat packages/yt/tool/publish_tools.yaml | yq -r '.commit')"; git push origin main
      description: Commit changes for lib package.

    commit:cli:
      run: melos exec --ignore="yt" git add .; git commit -m "$(cat packages/yt_cli/tool/publish_tools.yaml | yq -r '.commit')"; git push origin main
      description: Commit changes for Flutter package.

    dryrun:lib:
      run: melos exec --ignore="yt_cli" dart pub publish --dry-run
      description: Run `dart pub publish --dry-run` for lib package.

    dryrun:cli:
      run: melos exec --ignore="yt" dart pub publish --dry-run
      description: Run `dart pub publish --dry-run` for cli package.

    analyze:
      exec: dart analyze .
      description: Run `dart analyze` in all packages.

    format:
      run: melos exec dart format .
      description: Run `dart format` for all packages.

    format-check:
      run: melos exec dart format . --set-exit-if-changed
      description: Run `dart format` checks for all packages.

    dartdoc:
      run: melos exec dart doc .
      description: Run dartdoc checks for all packages.

    markdown:
      run: melos exec grind 'pt-markdown'
      description: Run markdown generator for all packages.

    meta:
      description: Run metadata generator for all packages.
      run: melos exec grind 'pt-meta'

    pana:
      run: melos exec pana --no-dartdoc .
      description: Run pana checks for all packages.

      # clean:deep:
      #   run: git clean -x -d -f -q
      #   description: Clean things very deeply, can be used to establish "pristine checkout" status.
