name: yt_cli
version: 2.2.6+2
description: A command-line interface for YouTube.
repository: https://github.com/faithoflifedev/yt
homepage: https://github.com/faithoflifedev/yt

funding:
  - https://www.buymeacoffee.com/faithoflif2

environment:
  sdk: ">=3.10.0 <4.0.0"

executables:
  yt:

resolution: workspace

dependencies:
  args: ^2.7.0
  dio: ^5.9.2
  googleapis_auth: ^2.2.0
  universal_io: ^2.3.1
  yt: ^2.2.6+2