/// DO NOT EDIT THIS FILE
/// THIS FILE IS AUTOMATICALLY OVER WRITTEN BY PublishTools
import 'dart:convert' show json;

final pubSpec = json.decode(
    '{"name":"yt","version":"2.2.4","homepage":"https://github.com/faithoflifedev/yt","environment":{"sdk":">=3.1.0 <4.0.0"},"description":"Native Dart interface to multiple YouTube REST APIs including the Data API.","dependencies":{"args":"^2.4.2","csv":"^5.0.2","dio":"^5.3.2","fling_pickle":"^0.4.3","googleapis_auth":"^1.4.1","http":"^1.1.0","http_parser":"^4.0.2","json_annotation":"^4.8.1","loggy":"^2.0.3","retrofit":"^4.0.1","stemmer":"^2.2.0","universal_io":"^2.2.2","yaml":"^3.1.2"},"dev_dependencies":{"build_runner":"^2.4.6","grinder":"^0.9.4","isar_generator":"^3.1.0+1","json_serializable":"^6.7.1","lints":"^2.1.1","pub_semver":"^2.1.4","publish_tools":"^0.1.0+11","pubspec":"^2.3.0","retrofit_generator":"^7.0.8"},"executables":{"yt":""},"repository":"https://github.com/faithoflifedev/yt"}');
