/// DO NOT EDIT THIS FILE
/// THIS FILE IS AUTOMATICALLY OVER WRITTEN BY PublishTools
import 'dart:convert' show json;

final pubSpec = json.decode(
    '{"name":"yt","version":"2.2.1","homepage":"https://github.com/faithoflifedev/yt","environment":{"sdk":">=2.19.2 <4.0.0"},"description":"Native Dart interface to multiple YouTube REST APIs including the Data API.","dependencies":{"args":"^2.4.2","csv":"^5.0.2","dio":"^5.2.1+1","fling_pickle":"^0.4.3","googleapis_auth":"^1.4.1","http":"^0.13.5","http_parser":"^4.0.2","json_annotation":"^4.8.1","loggy":"^2.0.3","retrofit":"^4.0.1","stemmer":"^2.2.0","universal_io":"^2.2.2","yaml":"^3.1.2"},"dev_dependencies":{"build_runner":"^2.4.5","grinder":"^0.9.4","isar_generator":"^3.1.0+1","json_serializable":"^6.7.0","lints":"^2.0.1","pub_semver":"^2.1.4","publish_tools":"^0.1.0+10","pubspec":"^2.3.0","retrofit_generator":"^7.0.1"},"executables":{"yt":""},"repository":"https://github.com/faithoflifedev/yt"}');
